BEGIN;

-- AIONE Product Asset foundation.
-- Product Truth: product images are business assets attached to one canonical Product;
-- employee/source filenames are preserved, while canonical filenames are generated by AIONE.
-- Channel folders/containers are technical mappings and must not redefine Product identity.

CREATE TABLE IF NOT EXISTS public.product_assets (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  asset_no INTEGER NOT NULL CHECK (asset_no > 0 AND asset_no <= 999),
  asset_type TEXT NOT NULL DEFAULT 'image' CHECK (asset_type IN ('image','document','video','other')),
  asset_role TEXT,
  source_provider TEXT,
  source_ref TEXT,
  source_url TEXT,
  original_name TEXT,
  canonical_name TEXT NOT NULL,
  mime_type TEXT,
  lifecycle_status TEXT NOT NULL DEFAULT 'registered'
    CHECK (lifecycle_status IN ('registered','formalized','published','failed','archived')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by_person_id TEXT,
  updated_by_person_id TEXT,
  record_version INTEGER NOT NULL DEFAULT 1,
  source_system TEXT NOT NULL DEFAULT 'aione',
  archived_at TIMESTAMPTZ,
  UNIQUE (product_id, asset_no),
  UNIQUE (product_id, canonical_name)
);

CREATE INDEX IF NOT EXISTS idx_product_assets_product_status
  ON public.product_assets(product_id, lifecycle_status, asset_no);
CREATE INDEX IF NOT EXISTS idx_product_assets_source
  ON public.product_assets(source_provider, source_ref)
  WHERE source_provider IS NOT NULL AND source_ref IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.channel_asset_containers (
  id TEXT PRIMARY KEY,
  channel TEXT NOT NULL,
  shop_ref TEXT NOT NULL,
  container_code TEXT NOT NULL,
  lifecycle_status TEXT NOT NULL DEFAULT 'active'
    CHECK (lifecycle_status IN ('active','full','paused','retired')),
  capacity_limit INTEGER CHECK (capacity_limit IS NULL OR capacity_limit > 0),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by_person_id TEXT,
  updated_by_person_id TEXT,
  record_version INTEGER NOT NULL DEFAULT 1,
  source_system TEXT NOT NULL DEFAULT 'aione',
  archived_at TIMESTAMPTZ,
  UNIQUE (channel, shop_ref, container_code)
);

CREATE INDEX IF NOT EXISTS idx_channel_asset_containers_active
  ON public.channel_asset_containers(channel, shop_ref, lifecycle_status, container_code);

CREATE TABLE IF NOT EXISTS public.channel_asset_mappings (
  id TEXT PRIMARY KEY,
  asset_id TEXT NOT NULL REFERENCES public.product_assets(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  shop_ref TEXT NOT NULL,
  container_id TEXT REFERENCES public.channel_asset_containers(id) ON DELETE SET NULL,
  external_path TEXT,
  external_asset_id TEXT,
  lifecycle_status TEXT NOT NULL DEFAULT 'planned'
    CHECK (lifecycle_status IN ('planned','uploading','active','failed','deleted')),
  last_synced_at TIMESTAMPTZ,
  last_error JSONB,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  record_version INTEGER NOT NULL DEFAULT 1,
  source_system TEXT NOT NULL DEFAULT 'aione',
  archived_at TIMESTAMPTZ,
  UNIQUE (asset_id, channel, shop_ref)
);

CREATE INDEX IF NOT EXISTS idx_channel_asset_mappings_channel
  ON public.channel_asset_mappings(channel, shop_ref, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_channel_asset_mappings_container
  ON public.channel_asset_mappings(container_id, lifecycle_status)
  WHERE container_id IS NOT NULL;

COMMIT;
