import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,"..");
const read=(r)=>fs.readFileSync(path.join(root,r),"utf8");
const must=(c,m)=>{if(!c)throw new Error(m)};

const page=read("pages/selection-workbench/home.html");
const selection=read("js/pages/selection-workbench.js");
const adapter=read("js/data/selection-workbench-adapter.js");
const workspace=read("js/components/universal-workspace.js");
const presenter=read("js/components/object-presenter.js");
const typeRail=read("js/components/type-rail.js");
const flow=read("js/components/flow-component.js");
const business=read("js/pages/business-page-template.js");
const css=read("css/pages/selection-workbench.css");
const system=read("js/miwa-system.js");

must(page.includes('id="miwa-selection-template-entry"'),"选品根页未变为薄入口");
for(const legacy of ["selection-page-head","selection-card-grid","selection-list-view","selection-metrics","selection-flow-track"]) must(!page.includes(legacy),`选品根页仍复制旧结构：${legacy}`);
for(const dep of ["mountLevel2EmptyBase","getTemplateRecipe","renderPageHeader","renderTypeRail","renderFlow","renderCoreMetrics","createUniversalWorkspace","renderObjectCards","renderObjectList","renderMiwaNineElements"]) must(selection.includes(dep),`选品迁移缺少标准组件调用：${dep}`);
must(selection.includes('getTemplateRecipe("standard-business")'),"选品未声明标准业务母版Recipe");
must(selection.includes('recipeId:"standard-business"'),"选品未挂载标准业务母版上下文");
must(!selection.includes("createObjectViewController"),"选品仍保留旧独立视图控制器");
must(adapter.includes('from "./preview-opportunities.js"'),"选品Adapter未复用现有商品机会数据层");
must(!adapter.includes("selectionOpportunities = ["),"选品Adapter复制了商品机会事实数据");
for(const type of ["直发选品","常规选品","产品开发"]) must(adapter.includes(type),`选品类型缺失：${type}`);
for(const stage of ["商品机会","数据录入","成本试算","智能定价","上架判断"]) must(adapter.includes(stage),`选品流程节点缺失：${stage}`);
must(selection.includes("importPreviewOpportunities"),"批量导入能力未保留");
must(selection.includes("openSelectionRecordDetail"),"商品机会详情入口未保留");
must(workspace.includes("filters")&&workspace.includes("data-workspace-filter-key"),"Universal Workspace未支持多条件筛选");
must(workspace.includes("paginateItems")&&workspace.includes("data-workspace-pagination"),"Universal Workspace未支持标准分页");
must(presenter.includes('variant === "rich-media"')&&presenter.includes("miwa-object-card--rich-media"),"标准Object Presenter未承接选品富卡片");
must(typeRail.includes("data-type-rail-select")&&business.includes("renderTypeRail"),"类型Rail尚未成为业务母版共享组件");
must(flow.includes("data-flow-key")&&flow.includes("count"),"统一流程组件未承接可点击/数量能力");
for(const control of ["搜索","筛选","排序","导入","导出","视图","重置"]) must(workspace.includes(control),`统一工作区缺少${control}`);
for(const col of ["3","4","6"]) must(selection.includes(`cardColumns:[3,4,6]`)||workspace.includes(col),"3/4/6列能力缺失");
must(!css.includes(".selection-page-head")&&!css.includes(".selection-card-grid")&&!css.includes(".selection-list-view"),"活动选品CSS仍含旧页面结构");
must(css.includes("selection-batch-dialog"),"选品特有批量导入样式未保留");
must(fs.existsSync(path.join(root,"recovery/legacy-pages-v1.5/selection-workbench.js")),"旧选品JS未进入recovery");
must(fs.existsSync(path.join(root,"recovery/legacy-pages-v1.5/selection-workbench-home.html")),"旧选品页面未进入recovery");
must(system.includes("initSelectionWorkbench"),"根路由未继续初始化选品工作台");
console.log("V1.5 selection legacy migration validation passed.");
