import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,"..");
const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");
const must=(c,m)=>{if(!c)throw new Error(m);};
const routes=read("js/config/route-registry.js");
const sidebar=read("js/config/sidebar-registry.js");
const system=read("js/miwa-system.js");
const page=read("js/pages/miwa-work-home.js");
const html=read("pages/work-home/template.html");
const core=read("backend/src/routes/core.js");
const ai=read("backend/src/ai/ai-secretary-service.js");
for(const [id,label] of [["work-all","全部工作"],["work-following","我的关注"],["work-business-crossborder","美和跨境"],["work-business-wholesale","美和批发"],["work-business-study-abroad","美和留学"]]) must(routes.includes(`"${id}": route("${id}", "${label}"`),`缺少工作之家结构路由 ${id}`);
must(sidebar.includes('label:"事业工作"')&&sidebar.includes("MIWA_BUSINESSES.map"),"Sidebar未按事业组织工作入口");
must(!sidebar.includes('label:"我的工作", route:"work-mine"'),"我的工作仍作为正式Sidebar入口");
must(system.includes("work-following")&&system.includes("work-business-crossborder"),"新工作路由未进入初始化链");
for(const token of ["publicationCover","publicationBackCover","publicationPage","publicationSpread","美和工作9问","第08章｜当前工作动态"]) must(page.includes(token),`工作概览未真正继承出版物母版：${token}`);
for(const token of ["data-work-view=\"card\"","data-work-view=\"list\"","data-work-search","data-work-business","data-work-team","data-work-project","data-work-sort"]) must(page.includes(token),`Work Browser缺少能力：${token}`);
must(html.includes("miwa-work-card-grid")&&html.includes("miwa-work-table"),"卡片/列表双视图样式缺失");
must(page.includes("☆ 关注")&&page.includes("★ 已关注")&&page.includes("work-following"),"关注前台未实现");
must(core.includes('router.post("/work-home/:id/follow"')&&core.includes('router.delete("/work-home/:id/follow"'),"关注API未实现");
must(core.includes('scope === "all"')&&core.includes("companyVisibleSql")&&core.includes("participant_role <> 'observer'"),"公司透明/关注不推送边界未实现");
must(core.includes("canRead: Boolean(personId && (related || isCompanyVisibleWork(row)))"),"看得到与能操作未分离");
must(ai.includes('visibility:"company"')&&ai.includes("inferBusinessCodeFromRoute"),"美和AI新建工作未写入事业/可见性元数据");
console.log("V1.9.33 Work Home V2 structure-upgrade validation passed.");
