import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const must=(c,m)=>{if(!c)throw new Error(m)};
const masterJs=read('js/components/miwa-publication-master.js');
const masterCss=read('css/components/miwa-publication-master.css');
const business=read('js/pages/miwa-business-home-book.js');
const company=read('js/pages/miwa-company-home-book.js');
const entry=read('js/miwa-system.js');
const index=read('index.html');
must(masterJs.includes('publicationBackCover'), 'back cover component missing');
must(masterJs.includes('publicationCoverSpread'), 'cover spread component missing');
must(masterJs.includes('preparePrintOrder'), 'print back-cover reordering missing');
must(masterCss.includes('container-name:miwa-book-stage'), 'content-space container missing');
must(masterCss.includes('@container miwa-book-stage (max-width:900px)'), 'single-page adaptive rule missing');
must(masterCss.includes('max-width:1499px'), 'medium desktop aside-collapse rule missing');
must(masterCss.includes('@page{size:A4 portrait'), 'A4 portrait print rule missing');
must(business.includes('关于《美和集团事业手册》'), 'business back cover missing');
must(company.includes('关于《美和集团经营管理手册》'), 'company back cover missing');
must(company.includes('publicationChapterSummary'), 'company closing/summary page missing');
must(entry.includes('miwa-company-home-book.js?v=20260827-v1.9.31.4-digital-publication'), 'company book entry not wired');
must(entry.includes('miwa-business-home-book.js?v=20260827-v1.9.31.4-digital-publication'), 'business book entry not wired');
must(index.includes('miwa-publication-master.css?v=20260827-v1.9.31.4'), 'publication master cache key missing');
console.log('V1.9.31.4 digital publication validation passed.');
