import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,"..");
const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");
const must=(c,m)=>{if(!c)throw new Error(m)};
const routes=read("js/config/route-registry.js");
const system=read("js/miwa-system.js");
const page=read("js/pages/miwa-work-home.js");
const html=read("pages/work-home/template.html");
const generic=read("pages/business-template/template.html");
const core=read("backend/src/routes/core.js");
must(routes.includes('work: route("work", "工作之家", "platform", { status: "active", page: "./pages/work-home/template.html" })'),"工作之家没有独立页面模板");
for(const id of ["work-mine","work-pending","work-active","work-waiting","work-completed"])must(routes.includes(`"${id}"`),`缺少工作之家子路由 ${id}`);
must(system.includes("initMiwaWorkHome")&&system.includes("WORK_HOME_ROUTES"),"工作之家没有独立初始化链");
must(html.includes("miwa-work-home-entry"),"工作之家模板入口缺失");
must(generic.includes("miwa-business-template-entry"),"标准业务页面通用模板入口缺失");
const staticBusinessRefs=(routes.match(/\.\/pages\/business-home\/template\.html/g)||[]).length;
must(staticBusinessRefs===1,"事业之家静态模板不应再被其他业务页面复用");
must(page.includes('/api/v1/work-home?limit=200')&&page.includes("aiProposalId")&&page.includes("美和AI"),"工作之家没有读取正式工作或Proposal来源");
must(core.includes('router.get("/work-home"')&&core.includes("owner_person_id=$1 OR created_by_person_id=$1"),"Backend缺少当前用户工作之家安全查询");
console.log("V1.9.29.1 Work Home restoration validation passed.");
